"""
Oracle v2 - Theme Collection
Popular color palettes adapted for the Oracle TUI.
Each entry stores a Textual Theme object plus display metadata.
"""

from textual.theme import Theme

ORACLE_THEMES = [
    {
        "name": "cathedral",
        "label": "Cathedral",
        "desc": "Dourado e carmesim clássico",
        "colors": ["#b8860b", "#6b0f1a", "#d4a843", "#c8b89a"],
        "theme": Theme(
            name="cathedral",
            primary="#b8860b",
            secondary="#6b0f1a",
            accent="#d4a843",
            warning="#d4a843",
            error="#cc0000",
            success="#2e7d32",
            foreground="#c8b89a",
            background="#0a0a0a",
            surface="#111113",
            panel="#1a1a1d",
            dark=True,
        ),
    },
    {
        "name": "dracula",
        "label": "Dracula",
        "desc": "Névoa roxa e presas",
        "colors": ["#bd93f9", "#ff79c6", "#50fa7b", "#f8f8f2"],
        "theme": Theme(
            name="dracula",
            primary="#bd93f9",
            secondary="#ff79c6",
            accent="#50fa7b",
            warning="#f1fa8c",
            error="#ff5555",
            success="#50fa7b",
            foreground="#f8f8f2",
            background="#282a36",
            surface="#21222c",
            panel="#343746",
            dark=True,
        ),
    },
    {
        "name": "nord",
        "label": "Nord",
        "desc": "Gelo ártico e aurora",
        "colors": ["#88c0d0", "#5e81ac", "#a3be8c", "#eceff4"],
        "theme": Theme(
            name="nord",
            primary="#88c0d0",
            secondary="#5e81ac",
            accent="#a3be8c",
            warning="#ebcb8b",
            error="#bf616a",
            success="#a3be8c",
            foreground="#eceff4",
            background="#2e3440",
            surface="#3b4252",
            panel="#434c5e",
            dark=True,
        ),
    },
    {
        "name": "monokai",
        "label": "Monokai Pro",
        "desc": "Clássico de código vibrante",
        "colors": ["#ffd866", "#ff6188", "#a9dc76", "#fcfcfa"],
        "theme": Theme(
            name="monokai",
            primary="#ffd866",
            secondary="#ff6188",
            accent="#a9dc76",
            warning="#ffd866",
            error="#ff6188",
            success="#a9dc76",
            foreground="#fcfcfa",
            background="#2d2a2e",
            surface="#353236",
            panel="#403e41",
            dark=True,
        ),
    },
    {
        "name": "gruvbox",
        "label": "Gruvbox",
        "desc": "Retro quente e terroso",
        "colors": ["#fabd2f", "#fb4934", "#b8bb26", "#ebdbb2"],
        "theme": Theme(
            name="gruvbox",
            primary="#fabd2f",
            secondary="#fb4934",
            accent="#b8bb26",
            warning="#fe8019",
            error="#fb4934",
            success="#b8bb26",
            foreground="#ebdbb2",
            background="#282828",
            surface="#3c3836",
            panel="#504945",
            dark=True,
        ),
    },
    {
        "name": "catppuccin",
        "label": "Catppuccin",
        "desc": "Suave mocha pastel",
        "colors": ["#cba6f7", "#f38ba8", "#a6e3a1", "#cdd6f4"],
        "theme": Theme(
            name="catppuccin",
            primary="#cba6f7",
            secondary="#f38ba8",
            accent="#a6e3a1",
            warning="#f9e2af",
            error="#f38ba8",
            success="#a6e3a1",
            foreground="#cdd6f4",
            background="#1e1e2e",
            surface="#181825",
            panel="#313244",
            dark=True,
        ),
    },
    {
        "name": "tokyonight",
        "label": "Tokyo Night",
        "desc": "Cidade neon após o anoitecer",
        "colors": ["#7aa2f7", "#bb9af7", "#9ece6a", "#c0caf5"],
        "theme": Theme(
            name="tokyonight",
            primary="#7aa2f7",
            secondary="#bb9af7",
            accent="#9ece6a",
            warning="#e0af68",
            error="#f7768e",
            success="#9ece6a",
            foreground="#c0caf5",
            background="#1a1b26",
            surface="#16161e",
            panel="#24283b",
            dark=True,
        ),
    },
    {
        "name": "rosepine",
        "label": "Rosé Pine",
        "desc": "Alvorecer e anoitecer suaves",
        "colors": ["#ebbcba", "#c4a7e7", "#f6c177", "#e0def4"],
        "theme": Theme(
            name="rosepine",
            primary="#ebbcba",
            secondary="#c4a7e7",
            accent="#f6c177",
            warning="#f6c177",
            error="#eb6f92",
            success="#31748f",
            foreground="#e0def4",
            background="#191724",
            surface="#1f1d2e",
            panel="#26233a",
            dark=True,
        ),
    },
    {
        "name": "solarized",
        "label": "Solarized",
        "desc": "Projetado com precisão",
        "colors": ["#268bd2", "#d33682", "#b58900", "#93a1a1"],
        "theme": Theme(
            name="solarized",
            primary="#268bd2",
            secondary="#d33682",
            accent="#b58900",
            warning="#cb4b16",
            error="#dc322f",
            success="#859900",
            foreground="#93a1a1",
            background="#002b36",
            surface="#073642",
            panel="#073642",
            dark=True,
        ),
    },
    {
        "name": "cyberpunk",
        "label": "Cyberpunk",
        "desc": "Sobrecarga de matriz neon",
        "colors": ["#00ff9f", "#ff00ff", "#00e5ff", "#e0e0e0"],
        "theme": Theme(
            name="cyberpunk",
            primary="#00ff9f",
            secondary="#ff00ff",
            accent="#00e5ff",
            warning="#ffea00",
            error="#ff1744",
            success="#00ff9f",
            foreground="#e0e0e0",
            background="#0a0a0f",
            surface="#12121a",
            panel="#1a1a25",
            dark=True,
        ),
    },
]
